# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Mixed Format/Spark CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "master"
      - "0.**"

  pull_request:
    branches:
      - "master"
      - "0.**"
    paths:
      - ".github/workflows/**"
      - "amoro-common/**"
      - "amoro-format-iceberg/**"
      - "amoro-format-mixed/amoro-mixed-hive/**"
      - "amoro-format-mixed/amoro-mixed-spark/**"
      - "pom.xml"
      - "tools/maven/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [ '8', '11' ]
        spark: [ '3.3', '3.5' ]
    name: Build with JDK ${{ matrix.jdk }}, spark-${{ matrix.spark }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'
          cache: maven
          check-latest: false

      - name: Validate checkstyle first
        run: ./mvnw validate

      - name: Build amoro-mixed-spark module
        run: |
          cd amoro-format-mixed/amoro-mixed-spark
          ../../mvnw clean package -am -DskipTests -Dspotless.check.skip=true -Pjava${{ matrix.jdk }} -Pspark-${{ matrix.spark }}

      - name: Code coverage
        uses: codecov/codecov-action@v3
        with:
          verbose: true
          flags: core
